# Generated by Django 6.0.1 on 2026-01-19 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('full_path', models.CharField(blank=True, max_length=1000)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('query_params', models.TextField(blank=True)),
                ('request_body', models.TextField(blank=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('duration_ms', models.FloatField(blank=True, help_text='Request duration in milliseconds', null=True)),
                ('error', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Log',
                'verbose_name_plural': 'API Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='app_apilog_timesta_cc879e_idx'), models.Index(fields=['method', '-timestamp'], name='app_apilog_method_fbe902_idx'), models.Index(fields=['status_code', '-timestamp'], name='app_apilog_status__200cd1_idx'), models.Index(fields=['user', '-timestamp'], name='app_apilog_user_id_7905a9_idx')],
            },
        ),
    ]
