# Generated by Django 6.0.1 on 2026-01-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_apitoken_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('cupcake', 'Cupcake'), ('bumblebee', 'Bumblebee'), ('emerald', 'Emerald'), ('corporate', 'Corporate'), ('synthwave', 'Synthwave'), ('retro', 'Retro'), ('cyberpunk', 'Cyberpunk'), ('valentine', 'Valentine'), ('halloween', 'Halloween'), ('garden', 'Garden'), ('forest', 'Forest'), ('aqua', 'Aqua'), ('lofi', 'Lofi'), ('pastel', 'Pastel'), ('fantasy', 'Fantasy'), ('wireframe', 'Wireframe'), ('black', 'Black'), ('luxury', 'Luxury'), ('dracula', 'Dracula'), ('cmyk', 'CMYK'), ('autumn', 'Autumn'), ('business', 'Business'), ('acid', 'Acid'), ('lemonade', 'Lemonade'), ('night', 'Night'), ('coffee', 'Coffee'), ('winter', 'Winter')], default='light', max_length=20),
        ),
    ]
