# Generated by Django 6.0.1 on 2026-01-23 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userprofile_theme_preference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('code', models.TextField(default='# Write your Python script here\nprint("Hello, World!")')),
                ('dependencies', models.TextField(blank=True, help_text="One package per line (e.g., 'requests==2.28.0')")),
                ('venv_path', models.CharField(blank=True, max_length=500)),
                ('venv_created', models.BooleanField(default=False)),
                ('venv_updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False, help_text='Allow other users to view/run')),
                ('last_status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='idle', max_length=20)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('last_success', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('execution_count', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Script',
                'verbose_name_plural': 'Scripts',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ScriptExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('stdout', models.TextField(blank=True)),
                ('stderr', models.TextField(blank=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('process_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trigger_type', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('api', 'API')], default='manual', max_length=20)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='app.script')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_executions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Script Execution',
                'verbose_name_plural': 'Script Executions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScriptSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cron_expression', models.CharField(help_text="Cron expression (e.g., '0 */6 * * *' for every 6 hours)", max_length=100)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='app.script')),
            ],
            options={
                'verbose_name': 'Script Schedule',
                'verbose_name_plural': 'Script Schedules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='script',
            index=models.Index(fields=['owner', '-updated_at'], name='app_script_owner_i_75fed2_idx'),
        ),
        migrations.AddIndex(
            model_name='script',
            index=models.Index(fields=['last_status'], name='app_script_last_st_fc1d64_idx'),
        ),
        migrations.AddIndex(
            model_name='scriptexecution',
            index=models.Index(fields=['script', '-created_at'], name='app_scripte_script__8f8bd7_idx'),
        ),
        migrations.AddIndex(
            model_name='scriptexecution',
            index=models.Index(fields=['status'], name='app_scripte_status_cd4d86_idx'),
        ),
    ]
