# Generated by Django 6.0.1 on 2026-01-28 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_script_scriptexecution_scriptschedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='dependencies_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash of dependencies for change detection', max_length=64),
        ),
        migrations.AddField(
            model_name='script',
            name='dependency_conflicts',
            field=models.TextField(blank=True, help_text='JSON list of detected dependency conflicts'),
        ),
    ]
