# Generated by Django 6.0.1 on 2026-01-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_add_schedule_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scriptschedule',
            name='calendar_expression',
        ),
        migrations.AddField(
            model_name='scriptschedule',
            name='interval_unit',
            field=models.CharField(blank=True, choices=[('hours', 'Hourly'), ('days', 'Daily'), ('weeks', 'Weekly'), ('months', 'Monthly')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='scriptschedule',
            name='interval_value',
            field=models.IntegerField(default=1, help_text='How many units between runs'),
        ),
        migrations.AddField(
            model_name='scriptschedule',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scriptschedule',
            name='cron_expression',
            field=models.CharField(blank=True, default='', help_text="Cron expression (e.g., '0 */6 * * *' for every 6 hours)", max_length=100),
        ),
        migrations.AlterField(
            model_name='scriptschedule',
            name='schedule_type',
            field=models.CharField(choices=[('cron', 'Cron'), ('single', 'Single datetime'), ('interval', 'Interval (repeating)')], default='single', max_length=20),
        ),
    ]
