# Generated by Django 6.0.1 on 2026-01-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_scriptschedule_calendar_expression_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptexecution',
            name='peak_cpu_percent',
            field=models.FloatField(blank=True, help_text='Peak CPU usage percentage', null=True),
        ),
        migrations.AddField(
            model_name='scriptexecution',
            name='peak_memory_mb',
            field=models.FloatField(blank=True, help_text='Peak memory usage in MB', null=True),
        ),
        migrations.AddField(
            model_name='scriptexecution',
            name='timed_out',
            field=models.BooleanField(default=False, help_text='Whether execution was terminated due to timeout'),
        ),
        migrations.AddField(
            model_name='scriptexecution',
            name='timeout_seconds',
            field=models.IntegerField(blank=True, help_text='Execution timeout in seconds', null=True),
        ),
    ]
