# Generated by Django 6.0.1 on 2026-01-30 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_scriptexecution_peak_cpu_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='time_format',
            field=models.CharField(choices=[('12', '12-hour (AM/PM)'), ('24', '24-hour')], default='24', max_length=2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(choices=[('UTC', 'UTC'), ('America/New_York', 'Eastern Time (ET)'), ('America/Chicago', 'Central Time (CT)'), ('America/Denver', 'Mountain Time (MT)'), ('America/Los_Angeles', 'Pacific Time (PT)'), ('America/Anchorage', 'Alaska Time (AKT)'), ('Pacific/Honolulu', 'Hawaii Time (HT)'), ('Europe/London', 'London (GMT/BST)'), ('Europe/Paris', 'Paris (CET/CEST)'), ('Europe/Berlin', 'Berlin (CET/CEST)'), ('Europe/Rome', 'Rome (CET/CEST)'), ('Europe/Madrid', 'Madrid (CET/CEST)'), ('Asia/Tokyo', 'Tokyo (JST)'), ('Asia/Shanghai', 'Shanghai (CST)'), ('Asia/Kolkata', 'India (IST)'), ('Asia/Dubai', 'Dubai (GST)'), ('Australia/Sydney', 'Sydney (AEST/AEDT)'), ('Australia/Melbourne', 'Melbourne (AEST/AEDT)'), ('Pacific/Auckland', 'Auckland (NZST/NZDT)')], default='UTC', max_length=50),
        ),
    ]
