# Generated by Django 6.0.1 on 2026-01-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_add_script_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('bash', 'Bash'), ('http', 'HTTP Request')], default='python', help_text='Script language/runtime', max_length=20),
        ),
    ]
