# Generated by Django for global credentials and MCP exposure

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_script_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for this credential', max_length=100)),
                ('credential_type', models.CharField(choices=[('api_key', 'API Key'), ('bearer_token', 'Bearer Token'), ('basic_auth', 'Basic Auth'), ('oauth_client_credentials', 'OAuth Client Credentials'), ('generic', 'Generic Key/Value')], default='generic', max_length=30)),
                ('encrypted_data', models.TextField(help_text='Encrypted credential data (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='auth.user')),
            ],
            options={
                'verbose_name': 'Global Credential',
                'verbose_name_plural': 'Global Credentials',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='script',
            name='expose_to_mcp',
            field=models.BooleanField(default=False, help_text='Make this script available as a tool through the MCP server'),
        ),
        migrations.AddField(
            model_name='script',
            name='credentials',
            field=models.ManyToManyField(blank=True, help_text='Global credentials to attach to this script', related_name='scripts', to='app.globalcredential'),
        ),
        migrations.AddIndex(
            model_name='globalcredential',
            index=models.Index(fields=['user', '-updated_at'], name='app_globalcredential_user_updated_idx'),
        ),
    ]