# Generated by Django 5.1.12 on 2026-06-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_script_mcp_tool_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='globalcredential',
            new_name='app_globalc_user_id_83cfa9_idx',
            old_name='app_globalcredential_user_updated_idx',
        ),
        migrations.AddField(
            model_name='scriptexecution',
            name='code_snapshot',
            field=models.TextField(blank=True, help_text='Snapshot of script code at time of execution'),
        ),
        migrations.AddField(
            model_name='scriptexecution',
            name='dependencies_snapshot',
            field=models.TextField(blank=True, help_text='Snapshot of script dependencies at time of execution'),
        ),
    ]
