# Generated by Django 5.1.12 on 2026-06-17 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_app_globalcredential_user_updated_idx_app_globalc_user_id_83cfa9_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptexecution',
            name='trigger_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('api', 'API'), ('mcp', 'MCP'), ('test', 'Test')], default='manual', max_length=20),
        ),
    ]
