"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load encrypted secrets (if master key and store present) into environment early
try:
    from app.services.secret_store import load_secrets_into_env

    load_secrets_into_env()
except Exception:
    # Best-effort: do not crash settings import if secrets can't be loaded
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Prefer secret from environment (populated from encrypted store), fall back to existing value
import os

SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY", "django_3yox@eft6cd_@&fg&its#g36!@ublj5qrsns6mc9@+2asvycvd"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

import os

# Read ALLOWED_HOSTS from environment, fall back to '*' in DEBUG (dev convenience)
_env_allowed = os.environ.get("ALLOWED_HOSTS")
if _env_allowed:
    ALLOWED_HOSTS = _env_allowed.split(",")
else:
    ALLOWED_HOSTS = ["*"] if DEBUG else []

# Application definition

INSTALLED_APPS = [
    "unfold",  # Must be before django.contrib.admin
    "unfold.contrib.filters",  # optional, if special filters are needed
    "unfold.contrib.forms",  # optional, if special form elements are needed
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "channels",  # WebSocket support
    "app",  # Main app for models and admin
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Serve static files with Daphne
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "app.middleware.APILoggingMiddleware",  # Log API requests
]

ROOT_URLCONF = "app.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "app.wsgi.application"
ASGI_APPLICATION = "app.asgi.application"

# Channels configuration
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
        # For production, use Redis:
        # 'BACKEND': 'channels_redis.core.RedisChannelLayer',
        # 'CONFIG': {
        #     "hosts": [('127.0.0.1', 6379)],
        # },
    },
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# PostgreSQL support via DATABASE_URL or individual POSTGRES_* variables
# Falls back to SQLite if neither is configured
import dj_database_url

def get_database_config():
    """Configure database from environment variables.
    
    Priority:
    1. DATABASE_URL (recommended)
    2. Individual POSTGRES_DB, POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_HOST, POSTGRES_PORT
    3. SQLite fallback for local development
    """
    # Try DATABASE_URL first (recommended for production)
    database_url = os.environ.get("DATABASE_URL")
    if database_url:
        return dj_database_url.parse(database_url, conn_max_age=600, conn_health_checks=True)
    
    # Try individual POSTGRES_* variables
    db_name = os.environ.get("POSTGRES_DB")
    db_user = os.environ.get("POSTGRES_USER")
    db_password = os.environ.get("POSTGRES_PASSWORD")
    db_host = os.environ.get("POSTGRES_HOST", "localhost")
    db_port = os.environ.get("POSTGRES_PORT", "5432")
    
    if db_name and db_user and db_password:
        return {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": db_name,
            "USER": db_user,
            "PASSWORD": db_password,
            "HOST": db_host,
            "PORT": db_port,
            "CONN_MAX_AGE": 600,
            "OPTIONS": {
                "sslmode": "require" if not DEBUG else "prefer",
            },
            # Connection pool options (psycopg3 async support)
            "DISABLE_SERVER_SIDE_CURSORS": False,
        }
    
    # SQLite fallback for local development
    return {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / 'db' / "db.sqlite3",
        "OPTIONS": {
            "timeout": 20,
        },
    }

DATABASES = {
    "default": get_database_config()
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "America/New_York"

USE_I18N = True

USE_TZ = True

CSRF_TRUSTED_ORIGINS = [
    "https://*.bhm.li",
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"

# Directory where `collectstatic` will collect static files for production
STATIC_ROOT = BASE_DIR / "staticfiles"

# Additional directories to look for static files (project-level)
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Optional (production): use WhiteNoise to serve static files. Install with:
# pip install whitenoise
# and add 'whitenoise.middleware.WhiteNoiseMiddleware' to MIDDLEWARE just after SecurityMiddleware.
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# CORS settings (for API access from same-origin Django templates)
# Since we're using Django templates on the same server, CORS is not strictly needed
# But keeping it configured for potential future external access
CORS_ALLOW_ALL_ORIGINS = True  # Set to True only for development testing
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

# Authentication settings
LOGIN_REDIRECT_URL = "/"
LOGIN_URL = "/login/"
LOGOUT_REDIRECT_URL = "/"

# Media files (uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# uv package manager (script virtual environments)
UV_EXECUTABLE = os.environ.get("UV_EXECUTABLE", "uv")
UV_CACHE_DIR = os.environ.get("UV_CACHE_DIR", str(BASE_DIR / ".cache" / "uv"))

# Email settings (for development - prints to console)
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
# For production, use:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your-email@gmail.com'
# EMAIL_HOST_PASSWORD = 'your-app-password'
DEFAULT_FROM_EMAIL = "noreply@mysite.com"

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Unfold Admin Configuration
from django.templatetags.static import static
from django.urls import reverse_lazy

UNFOLD = {
    "SITE_TITLE": "Python Script Runner",  # Shows in browser tab
    "SITE_HEADER": "Python Script Runner",  # Shows in admin header
    "SITE_URL": "/",
    "SITE_ICON": None,  # Optional - add your favicon path here
    "SITE_LOGO": None,  # Optional - add your logo path here
    "SITE_SYMBOL": "code",  # Material icon name for the site symbol
    "SHOW_HISTORY": True,  # Show history on detail pages
    "SHOW_VIEW_ON_SITE": True,  # Show "view on site" button
    # Custom colors (comment this out and use "THEME" below for built-in themes)
    "COLORS": {
        "primary": {
            # Purple/Blue gradient to match daisyUI primary
            "50": "245 243 255",
            "100": "237 233 254",
            "200": "221 214 254",
            "300": "196 181 253",
            "400": "167 139 250",
            "500": "139 92 246",  # Main primary color
            "600": "124 58 237",
            "700": "109 40 217",
            "800": "91 33 182",
            "900": "76 29 149",
            "950": "46 16 101",
        },
    },
    # OR use a built-in theme (uncomment this and remove COLORS above)
    # "THEME": "blue",  # Options: "green", "blue", "purple", "red", "yellow", "monochrome"
    "SIDEBAR": {
        "show_search": True,  # Show search in sidebar
        "show_all_applications": True,  # Show all apps in sidebar
        # Navigation will be automatically generated from your apps/models
    },
}
